
site_name: "Hunt Down The Freeman: Tech Docs"
site_description: 'Docs for features in HDTF'
site_author: 'Nbc66'
site_url: 'https://nbc66.github.io/hdtf_docs/'

repo_url: https://github.com/Nbc66/hdtf_docs
repo_name: "Nbc66/hdtf_docs"

# site_name: "Hunt Down The Freeman: Technical Documentation"

plugins:
  - search
  - glightbox:
       touchNavigation: true
       loop: false
       effect: fade
       slide_effect: slide
       width: 100vh
       height: auto
       zoomable: true
       draggable: true
       auto_caption: false
       caption_position: bottom
  - macros:
      include_dir: _includes


theme:
  features:
    - navigation.tabs
  favicon: images/icon/hdtf_icon.jpg
  logo: images/icon/hdtf_icon.jpg
  name: material
  palette:
    scheme: slate
    accent: red
    primary: custom
  highlightjs: true
  custom_dir: 'theme'
  hljs_languages:
     - yaml
     - rust
     - c++
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
